### ISSUE TITLE
Add support for self-hosted github repos

### ISSUE THREAD

**Issue by ventsyv** [MeilCli/bump-release-action#741]
There are a couple of hard coded github.com URLs. This prevents the action from working on a self-hosted github instances.

Add a base_url configuration option and replace the github.com URLs with that value.

**Comment by MeilCli** [comment]
@ventsyv 
Thanks your issue reporting and contributing

I published [v1.6.0](https://github.com/MeilCli/bump-release-action/releases/tag/v1.6.0). That version includes your contributing.

Thanks.
